import 'react-loading-skeleton/dist/skeleton.css'
import Skeleton from 'react-loading-skeleton'
import { TrLoading } from './styles'

export function TasksLoading() {
  return (
    <>
      <TrLoading>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
      </TrLoading>
      <TrLoading>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
      </TrLoading>
    </>
  )
}
