import 'react-loading-skeleton/dist/skeleton.css'
import Skeleton from 'react-loading-skeleton'
import { TrContainer } from './styles'

export function ListViewLoading() {
  return (
    <>
      <TrContainer>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
      </TrContainer>
      <TrContainer>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
      </TrContainer>
      <TrContainer>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
      </TrContainer>
      <TrContainer>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
      </TrContainer>
      <TrContainer>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
        <td>
          <Skeleton
            baseColor="#3F3F46"
            highlightColor="#71717A"
            height={50}
            borderRadius={6}
          />
        </td>
      </TrContainer>
    </>
  )
}
